version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          name: Setup Miniconda
          command: |
              wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh;
              chmod +x ~/miniconda.sh && ~/miniconda.sh -b;
              echo 'export PATH="$HOME/miniconda3/bin:$PATH"'  >> $BASH_ENV;
      - run:
          name: Build Environment
          command: |
            conda activate base
            conda install -r requirements.txt
            conda install install -y \
                  libhdf5-dev \
                  cmake \
                  gfortran \
                  libblas-dev \
                  liblapack-dev \
                  libeigen3-dev \
                  libhdf5-serial-dev \
                  autoconf \
                  libtool \
                  doxygen \
                  hdf5-tools \
                  cyclus \
                  cymetric

      - run:
          name: Test transition-scenarios
          command: |
            cd ~/project/scripts/tests/
            pytest

workflows:
  version: 2.1
  main:
    jobs:
      - build-and-test
            cd ~/project/scripts/tests/
            pytest

workflows:
  version: 2.1
  main:
    jobs:
      - build-and-test
