name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.11.9  # Specify the Python version you need

    - name: Create environment and install dependencies
      run: |
        conda init bash
        conda config --add channels conda-forge
        source ~/.bashrc
        conda create --name test-env python=3.11.9 -y
        conda activate test-env
        pip install -r requirements.txt
        conda install -y \
          hdf5 \
          cmake \
          gfortran \
          libblas \
          liblapack \
          omnia::eigen3 \
          autoconf \
          libtool \
          doxygen \
          progress

    - name: Install Cymetric
      run: |
        source ~/.bashrc
        conda activate test-env
        conda install -y cymetric

    - name: Install Pyne
      run: |
        source ~/.bashrc
        export PATH="/home/circleci/.local/bin:${PATH}"
        export PYTHONPATH='/home/circleci/.local/:${PYTHONPATH}'
        mkdir github
        git clone https://github.com/pyne/pyne
        cd pyne/
        python setup.py install --user
        cd ~/
        nuc_data_make

    - name: Run tests
      run: |
        source ~/.bashrc
        conda activate test-env
        pytest